Router.configure({
  layoutTemplate: 'ApplicationLayout'
});

Router.route('/','index');
Router.route('/about.html','about');
Router.route('/altpage.html','altpage');
Router.route('/blog-fullwidth.html','blog-fullwidth');
Router.route('/blog.html','blog');
Router.route('/contact.html','contact');
Router.route('/docs.html','docs');
Router.route('/elements.html','elements');
Router.route('/faq.html','faq');
Router.route('/fullbg.html','fullbg');
Router.route('/icons.html','icons');
Router.route('/portfolio-3col-squared.html','portfolio-3col-squared');
Router.route('/portfolio-3col.html','portfolio-3col');
Router.route('/portfolio-4col.html','portfolio-4col');
Router.route('/portfolio-item.html','portfolio-item');
Router.route('/post.html','post');
Router.route('/pricing.html','pricing');
Router.route('/services.html','services');
Router.route('/sidebar-left.html','sidebar-left');
Router.route('/sidebar-right.html','sidebar-right');
Router.route('/tables.html','tables');
Router.route('/testimonials.html','timeline');
Router.route('/timeline.html','timeline');
Router.route('/typography.html','typography');
Router.route('/404.html','404');
